- Swift/가운데_글자_가져오기.swift
https://programmers.co.kr/learn/courses/30/lessons/12903
> 🔀 Swift :: 프로그래머스 - 가운데 글자 가져오기

- JavaScript/[1차]비밀지도
https://programmers.co.kr/learn/courses/30/lessons/17681 문제 풀이
> 🔀 [1차] 비밀지도

- Swift/다리_놓기.swift
https://www.acmicpc.net/problem/1010
> 🔀 :: 백준 :: 다리 놓기 - Swift

- Swift/자연수_뒤집어_배열로_만들기.swift
https://programmers.co.kr/learn/courses/30/lessons/12932
> 🔀 프로그래머스 :: 자연수 뒤집어 배열로 만들기

- Swift/[1차]비밀지도.swift
https://programmers.co.kr/learn/courses/30/lessons/17681
> 🔀 프로그래머스 :: [1차]비밀지도

- Swift/약수의_합.swift
https://programmers.co.kr/learn/courses/30/lessons/12928
> 🔀 프로그래머스 :: 약수의 합

- Swift/나누어_떨어지는_숫자_배열.swift
https://programmers.co.kr/learn/courses/30/lessons/12910
> 🔀 프로그래머스 :: 나누어 떨어지는 숫자 배열

- Swift/직사각형_별찍기.swift
https://programmers.co.kr/learn/courses/30/lessons/12969
> 🔀 :: 프로그래머스 - 직사각형 별찍기

- Swift/이상한_문자_만들기.swift
https://programmers.co.kr/learn/courses/30/lessons/12930
> 🔀 :: 프로그래머스 - 이상한 문자 만들기

- Swift/문자열을_정수로_바꾸기.swift
https://programmers.co.kr/learn/courses/30/lessons/12925
날먹 냠냠
> 🔀 :: 프로그래머스 - 문자열을 정수로 바꾸기

- Swift/문자열_내_마음대로_정렬하기.swift
https://programmers.co.kr/learn/courses/30/lessons/12915
> 🔀 :: 프로그래머스 - 문자열 내 마음대로 정렬하기

- Swift/문자열_다루기_기본.swift
https://programmers.co.kr/learn/courses/30/lessons/12918
> 🔀 :: 프로그래머스 - 문자열 다루기 기본

- Swift/서울에서_김서방_찾기.swift
https://programmers.co.kr/learn/courses/30/lessons/12919
> 🔀 :: 프로그래머스 - 서울에서 김서방 찾기

- Swift/문자열_내림차순으로_정렬하기.swift
https://programmers.co.kr/learn/courses/30/lessons/12917
> 🔀 :: 프로그래머스 - 문자열 내림차순으로 정렬하기

- Swift/문자열_내_p와_y의_개수.swift
https://programmers.co.kr/learn/courses/30/lessons/12916
> 🔀 :: 프로그래머스 - 문자열 내 p와 y의 개수

- Swift/수박수박수박수박수박수?.swift
https://programmers.co.kr/learn/courses/30/lessons/12922
> 🔀 :: 프로그래머스 - 수박수박수박수박수박수?

- Swift/소수_찾기.swift
https://programmers.co.kr/learn/courses/30/lessons/12921
> 🔀 :: 프로그래머스 - 소수 찾기

- Swift/[1차]다트게임.swift
https://programmers.co.kr/learn/courses/30/lessons/17682
> 🔀 :: 프로그래머스 - [1차]다트게임

- Swift/시저_암호.swift
https://programmers.co.kr/learn/courses/30/lessons/12926
> 🔀 :: 프로그래머스 - 시저 암호

- Swift/정수_내림차순으로_정렬하기.swift
https://programmers.co.kr/learn/courses/30/lessons/12933
> 🔀 :: 프로그래머스 - 정수 내림차순으로 정렬하기

- Swift/짝수와_홀수.swift
https://programmers.co.kr/learn/courses/30/lessons/12937
> 🔀 :: 프로그래머스 - 짝수와 홀수

- Swift/제일_작은_수_제거하기.swift
https://programmers.co.kr/learn/courses/30/lessons/12935
> 🔀 :: 프로그래머스 - 제일 작은 수 제거하기

- Swift/피보나치_수.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12945
> 🔀 :: 피보나치 수

- Swift/균형잡힌_세상.swift
https://www.acmicpc.net/problem/4949
> 🔀 :: 백준 - 균형잡힌 세상

- Swift/예상_대진표.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12985
> 🔀 :: 프로그래머스 - 예상 대진표

- Python/내적.py
- Python/오픈채팅방.py
> ✨ :: 프로그래머스 - 내적, 오픈채팅방

- Python/최소직사각형.py
구현은 쉬웠어서 개발자가 아닌 코더가 된거 같아서 현타가 온다..
> 🔀 : :: 프로그래머스 - 최소직사각형

- Kotlin/숫자_문자열과_영단어.kt
- Kotlin/오픈채팅방.kt
> 🔀 :: 프로그래머스 - 오픈채팅방

- Python/성격_유형_검사하기.py
- Python/숫자_문자열과_영단어.py
> :sparkles: :: 프로그래머스 - 숫자 문자열과 영단어

- Swift/그릇.swift
https://www.acmicpc.net/problem/7567
> 🔀 :: 백준 - 그릇

- Swift/완전제곱수.swift
https://www.acmicpc.net/problem/1977
> 🔀 :: 백준 - 완전제곱수

- Swift/생일.swift
https://www.acmicpc.net/problem/5635
> 🔀 :: 백준 - 생일

- Swift/두_큐_합_같게_만들기.swift
> 🔀 :: 프로그래머스 - 두 큐 합 같게 만들기

- Swift/행렬의_덧셈.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12950
> 🔀 :: 프로그래머스 - 행렬의 덧셈

- Swift/[1차]캐시.swift
https://school.programmers.co.kr/learn/courses/30/lessons/17680
> 🔀 :: 프로그래머스 - [1차]캐시

- Swift/x만큼_간격이_있는_n개의_숫자.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12954
> 🔀 :: 프로그래머스 - x만큼 간격이 있는 n개의 숫자

- Swift/정수_제곱근_판별.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12934
> 🔀 :: 정수 제곱근 판별

- Swift/핸드폰_번호_가리기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12948
> 🔀 :: 핸드폰 번호 가리기

- Swift/콜라즈_추측.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12943
> 🔀 :: 프로그래머스 - 콜라즈 추측

- Swift/평균_구하기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12944
> 🔀 :: 프로그래머스 - 평균 구하기

- Swift/하샤드_수.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12947
> 🔀 :: 프로그래머스 - 하샤드 수

- Swift/최대공약수와_최소공배수.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12940
> 🔀 :: 프로그래머스 - 최대공약수와 최소공배수

- Swift/성격_유형_검사하기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/118666
> 🔀 :: 프로그래머스 - 성격 유형 검사하기

- Swift/올바른_괄호.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12909
> 🔀 :: 올바른 괄호

- Swift/거리두기_확인하기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/81302
> 🔀 :: 프로그래머스 - 거리두기 확인하기

- Swift/문자열_압축.swift
https://school.programmers.co.kr/learn/courses/30/lessons/60057
> 🔀 :: 프로그래머스 - 문자열 압축

- Python/거리두기_확인하기.py
다 풀어놓고 개 간단한거 하나 확인못해서 하루 날림 ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ
> 🔀 : :: 프로그래머스 - 거리두기 확인하기

- Kotlin/가운데 글자 가져오기.kt
> 🔀 :: 프로그래머스 - 가운데 글자 가져오기

- Kotlin/부족한_금액_계산하기.kt
> 🔀  ::  프로그래머스 - 부족한 금액 계산하기

- Kotlin/나누어_떨어지는_배열.kt
> 🔀 :: 프로그래머스 - 나누어 떨어지는 배열

- Kotlin/2016년.kt
https://school.programmers.co.kr/learn/courses/30/lessons/12901
> 🔀 :: 2016년

- Kotlin/서울에서_김서방_찾기.kt
https://school.programmers.co.kr/learn/courses/30/lessons/12919
> 🔀 :: 프로그래머스-서울에서김서방 찾기

- Kotlin/문자열_내림차순_배치.kt
https://school.programmers.co.kr/learn/courses/30/lessons/12917
> 🔀 :: 프로그래머스-문자열 내림차순으로 배치하기

- Kotlin/단어의 개수.kt
> 🔀 :: 백준 - 단어의 개수

- Kotlin/거스름돈.kt
> 🔀 :: 백준 - 거스름돈

- Swift/햄버거_만들기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/133502
> 🔀 :: 프로그래머스 - 햄버거 만들기

- Swift/옹알이_(2).swift
https://school.programmers.co.kr/learn/courses/30/lessons/133499
> 🔀 :: 프로그래머스 - 옹알이(2)

- Swift/콜라_문제.swift
https://school.programmers.co.kr/learn/courses/30/lessons/132267
> 🔀 :: 콜라 문제

- Swift/공원_산책.swift
https://school.programmers.co.kr/learn/courses/30/lessons/172928
> 프로그래머스 Swift - 공원 산책

- Swift/광물_캐기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/172927
> 프로그래머스 Swift - 광물 캐키

- Swift/섬_연결하기.swift
https://school.programmers.co.kr/learn/courses/30/lessons/42861
> 프로그래머스 Swift - 섬 연결하기

- Swift/불량_사용자.swift
https://school.programmers.co.kr/learn/courses/30/lessons/64064
> 프로그래머스 Swift - 불량 사용자

- Swift/이중우선순위큐.swift
https://school.programmers.co.kr/learn/courses/30/lessons/42628
> 프로그래머스 Swift - 이중우선순위큐

- Kotlin/모의고사.kt
모의고사 화이팅!
https://school.programmers.co.kr/learn/courses/30/lessons/42840
> 🔀 :: 프로그래머스 - 모의고사

- Swift/기지국_설치.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12979
> 프로그래머스 Swift - 기지국 설치

- Swift/베스트_앨범.swift
https://school.programmers.co.kr/learn/courses/30/lessons/42579
> 프로그래머스 Swift - 베스트 앨범

- Swift/숫자_게임.swift
https://school.programmers.co.kr/learn/courses/30/lessons/12987
> 프로그래머스 Swift - 숫자 게임

- Swift/네트워크.swift
https://school.programmers.co.kr/learn/courses/30/lessons/43162
> 프로그래머스 Swift - 네트워크

- Swift/두_원_사이의_정수_쌍.swift
https://school.programmers.co.kr/learn/courses/30/lessons/181187
> 프로그래머스 Swift - 두 원 사이의 정수 쌍

- Swift/단어_변환.swift
https://school.programmers.co.kr/learn/courses/30/lessons/43163
> 프로그래머스 Swift - 단어 변환

- Swift/가장_많이_받은_선물.swift
https://school.programmers.co.kr/learn/courses/30/lessons/258712
> 프로그래머스 Swift - 가장 많이 받은 선물

- Swift/달리기_경주.swift
https://school.programmers.co.kr/learn/courses/30/lessons/178871
> 프로그래머스 Swift - 달리기 경주
